name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Mirzapur 1080P"
  comment: "Mirzapur 1080P"
  url: "https://index.cdn-utube.workers.dev/2417422473a10942cf91c46826cdac9274c9d5180b79ad512a8bcc07f18ac9fbc06cf17b18f9d8df4fe3851a762ab08c::a3e9bc2a24c2057df7eb2d3d25602e75/1396595190/HDMovies4u.Boo-Mirzapur.S01.E01-09.1080p.AMZN.WEB-DL.DD+5.1.H.264.zip"
  file_name: "HDMovies4u.Boo-Mirzapur.S01.E01-09.1080p.AMZN.WEB-DL.DD+5.1.H.264.zip"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: mirzapur
          path: mirzapur.torrent
